// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTag: typeof import('element-plus/es')['ElTag']
    MainBody: typeof import('./src/components/MainBody.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    VoiceCard: typeof import('./src/components/VoiceCard.vue')['default']
  }
}

export {}
